server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_test
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false
#    It is for mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/spring_project?
#  useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
#    username: ?
#    password: ?
